apiVersion: v1
kind: Pod
metadata:
  name: spc-pod
  labels:
    app: spc
spec:
  containers:
    - name: spc-container
      image: 239500134360.dkr.ecr.ap-south-1.amazonaws.com/dev/spcimage:latest
      ports:
        - containerPort: 8080