name: Java-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spc
    runs-on: ubuntu-latest

    steps:
      - name: Gitcheckout
        uses: actions/checkout@v4

      - name: Build java with maven
        run: mvn package

      - name: Build and Analyze
        uses: SonarSource/sonarqube-scan-action@v2   # ✅ correct version

        env:
          SONAR_TOKEN: ${{ secrets.spc }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

        with:
          args: >
            -Dsonar.organization=ShivanandiniSaddanapu
            -Dsonar.projectName=petclinic
            -Dsonar.projectKey=shivanandinisaddanapu